version: '3'

################################################################################################
#
# local dev:
#   - run:
#   - clean:
#
################################################################################################


#
# sub namespace: https://taskfile.dev/#/usage?id=including-other-taskfiles
#
includes:
  ui:
    taskfile: packages/better_ui/Taskfile.yml
    dir: packages/better_ui/ # global path
    optional: true # safeguard, if not found, no error


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  PKG_WEB3: "packages/web3"
  PKG_BETTER_UI: "packages/better_ui"
  PKG_KIT: "packages/kit"
  PKG_kit: "packages/kit"


# global env:
env:
  ENV1: testing

# env file:
dotenv:
  - .env

################################################################################################


# task groups:
tasks:
  default:
    cmds:
      - task: init

  init:
    cmds:
      - cp .env.local .env
      - task: get-kit
      - task: get-web3
      - task: get-wallet-connect
      - task: get-better-ui

  #########################################################################

  get-kit:
    cmds:
      - task: get
        vars: {PKG_DIR: "packages/kit"}

  get-web3:
    cmds:
      - task: get
        vars: {PKG_DIR: "packages/web3"}

  get-wallet-connect:
    cmds:
      - task: get
        vars: {PKG_DIR: "packages/wallet_connect"}

  get-better-ui:
    cmds:
      - task: get
        vars: {PKG_DIR: "packages/better_ui"}

  get:
    cmds:
      - cd {{.PKG_DIR}}; fvm flutter pub get

  #########################################################################

  publish:
    cmds:
      - PUB_HOSTED_URL=https://pub.dartlang.org; FLUTTER_STORAGE_BASE_URL=https://storage.dartlang.org; cd {{.PKG_DIR}}; dart pub publish -v # --dry-run
      - task: publish-version-check

  publish-version-check:
    cmds:
      - echo 'shoud update >> pubspec.yaml pkg version'
      - echo 'shoud update >> CHANGELOG.md '

  publish-check-web3:
    cmds:
      - task: publish-check
        vars: {PKG_DIR: "packages/web3"}

  publish-check:
    cmds:
      - cd {{.PKG_DIR}}; dart pub publish --dry-run

  publish-kit:
    cmds:
      - task: publish
        vars: {PKG_DIR: "packages/kit"}

  publish-web3:
    cmds:
      - task: publish
        vars: {PKG_DIR: "packages/web3"}

  publish-better-ui:
    cmds:
      - task: publish
        vars: {PKG_DIR: "packages/better_ui"}

  publish:better-app:
    cmds:
      - task: publish
        vars: {PKG_DIR: "packages/better_app"}

  publish:better-cli:
    cmds:
      - task: publish
        vars: {PKG_DIR: "packages/better_cli"}


  #########################################################################

  pkg:new:
    cmds:
      - cd packages; fvm flutter create --template=package $NEW_PKG_NAME

  pub-proxy: # fix error: template not found
    cmds:
      - export PUB_HOSTED_URL=https://pub.dartlang.org; \
        export FLUTTER_STORAGE_BASE_URL=https://storage.dartlang.org;



  activate:
    cmds:
      - pub global activate melos


  clean:
    cmds:
      - melos clean
      - fvm flutter clean

  melos-init:
    cmds:
      - melos bootstrap # fix error: do not use pub get proxy url

  melos-clean:
    cmds:
      - melos clean

  version-check:
    cmds:
      - fvm releases
      - fvm list

  mkdir:
    desc: "create app folder"
    cmds:
      - mkdir -p {{.FOLDER}}

  #########################################################################

  push:
    cmds:
      - git push origin main --tags
