version: '3'


# task groups:
tasks:
  default:
    cmds:
      - echo "hello better_ui"

  get:
    cmds:
      - fvm flutter pub get

  publish:test:
    cmds:
      - |
        PUB_HOSTED_URL=https://pub.dartlang.org; \
        FLUTTER_STORAGE_BASE_URL=https://storage.dartlang.org; \
        dart pub publish -v --dry-run

  publish:
    cmds:
      - |
        PUB_HOSTED_URL=https://pub.dartlang.org; \
        FLUTTER_STORAGE_BASE_URL=https://storage.dartlang.org; \
        dart pub publish -v # --dry-run
